Here is the hand calculated examples of the end to end tests

In [10]:
#imports
import sys
import numpy as np
sys.path.append('../../SWE')
from aux_functions import f, discritization 
from numerical_schemes import lax_friedrich, godunov_upwind, tvd_waf

In [15]:
# test1 lax_friedrich
W = np.array([[0.5,1,1], [0.5,1,1],[10,-2,0], [3,2,0], [3,2,0]])
U = np.empty((5,3))
U[:,0], U[:,1], U[:,2] = W[:,0], W[:,0]*W[:,1], W[:,0]*W[:,2] 
print(str(U))
dt = discritization.center_dt(W, 0.1, 3, 9.8, 0.9)
fluxes = np.array([f.flux_from_w(W[1,:], 9.8), f.flux_from_w(W[2,:], 9.8), f.flux_from_w(W[3,:], 9.8)])
print(str(fluxes))
lax_l_flux = 1/2*(fluxes[0]+fluxes[1])+1/2*0.1/dt*(U[1,:]-U[2,:])
lax_r_flux = 1/2*(fluxes[1]+fluxes[2])+1/2*0.1/dt*(U[2,:]-U[3,:])
print("lax flux left: " + str(lax_l_flux) + "lax flux right: " + str(lax_r_flux))
new_U = U[2]-dt/0.1*(lax_r_flux-lax_l_flux)
print("U after operations: " + str(new_U) + "dt after operations: " + str(dt))

[[  0.5   0.5   0.5]
 [  0.5   0.5   0.5]
 [ 10.  -20.    0. ]
 [  3.    6.    0. ]
 [  3.    6.    0. ]]
[[ 5.000e-01  1.725e+00  5.000e-01]
 [-2.000e+01  5.300e+02 -0.000e+00]
 [ 6.000e+00  5.610e+01  0.000e+00]]
lax flux left: [-72.55288994 401.38452567   3.55541526]lax flux right: [ 39.27581364 121.16840647   0.        ]
U after operations: [1.54200798 1.19371525 0.26890837]dt after operations: 0.0075633462159047865
